// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBj0jZYd_DJIJ8NRid7-mJ_mki4IMH33Q',
    appId: '1:556577233916:web:6d1df451a561ef52573079',
    messagingSenderId: '556577233916',
    projectId: 'bd2trab6',
    authDomain: 'bd2trab6.firebaseapp.com',
    storageBucket: 'bd2trab6.appspot.com',
    measurementId: 'G-MCHZRRGF6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaoqASyX6jXicef0ylLcW_ASvu7-02Ca8',
    appId: '1:556577233916:android:5699cc6ac9504b16573079',
    messagingSenderId: '556577233916',
    projectId: 'bd2trab6',
    storageBucket: 'bd2trab6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL59Oqxys-isvHFkm6lVOjiNuT67ZX8hk',
    appId: '1:556577233916:ios:6bdea0a91982f728573079',
    messagingSenderId: '556577233916',
    projectId: 'bd2trab6',
    storageBucket: 'bd2trab6.appspot.com',
    iosBundleId: 'com.example.bd2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL59Oqxys-isvHFkm6lVOjiNuT67ZX8hk',
    appId: '1:556577233916:ios:fc199534aaeed878573079',
    messagingSenderId: '556577233916',
    projectId: 'bd2trab6',
    storageBucket: 'bd2trab6.appspot.com',
    iosBundleId: 'com.example.bd2.RunnerTests',
  );
}
